image: ubuntu:20.04

test: 
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip
    - pip install -r requirement.txt
    - cd src
    #- flake8 --statistics ## if I'm feeling nasty
    - pytest -v --cov

